# For more info, see http://about.travis-ci.org/docs/user/ci-environment/
language: node_js
node_js: ["0.8", "0.10"]
 
# Install Haxe (and Neko) before running the test.
before_script:
    - sudo add-apt-repository ppa:eyecreate/haxe -y
    - sudo apt-get update -y
    - sudo apt-get install haxe -y
    - mkdir -p ~/.haxe/lib
    - haxelib setup ~/.haxe/lib
 
# Run the test!
script:
  - haxe test/travis.hxml