# For more info, see http://about.travis-ci.org/docs/user/ci-environment/
language: node_js
node_js: ["0.10"]

os:
  - linux
  - osx
 
# Install Haxe (and Neko) before running the test.
# Also install haxelib libraries
before_script:
    - sudo add-apt-repository ppa:eyecreate/haxe -y
    - sudo apt-get update -y
    - sudo apt-get install haxe -y
    - mkdir -p ~/.haxe/lib
    - haxelib setup ~/.haxe/lib
    - haxelib install hx-yaml
    - haxelib install hx-ash
    - cd test
    - mkdir build
    - mkdir build/html5
    - mkdir build/neko
    - mkdir build/flash
 
# Run the test!
script:
  - haxe test.hxml
