# For more info, see http://about.travis-ci.org/docs/user/ci-environment/
language: node_js
node_js: ["0.10"]

os:
  - linux
  - osx
 
# Install Haxe (and Neko) before running the test.
# Also install haxelib libraries
before_script:
    - sudo add-apt-repository ppa:eyecreate/haxe -y
    - sudo apt-get update -y
    - sudo apt-get install haxe -y
    - sudo apt-get install gcc-multilib g++-multilib -y
    - mkdir -p ~/.haxe/lib
    - haxelib setup ~/.haxe/lib
    - haxelib install hxcpp
    - haxelib install yaml
    - haxelib install hx-ash
    - haxelib git flow https://github.com/underscorediscovery/flow.git
    - haxelib git snow https://github.com/underscorediscovery/snow.git
    - haxelib git luxe https://github.com/underscorediscovery/luxe.git
    - cd test
 
# Run the test!
script:
  - haxelib run flow run
